### ISSUE TITLE
rtimes anchor hyperlink doesn't work

### ISSUE THREAD

**Issue by engineerchange** [bradleyboehmke/bradleyboehmke.github.io#1]
The code on post **2016-01-18-scraping-via-apis.md**

```
<a href="#rtimes">`rtimes`</a> for pulling data from multiple APIs offered by the New York Times
```

references a named anchor "rtimes" that doesn't exist in the document.

**Comment by bradleyboehmke** [comment]
I see there is an html issue where the hyperlink is supposed to go (you can see it further down the page). This is an old blog post that I have since moved [here](http://uc-r.github.io/scraping). The link in this blog post works (http://uc-r.github.io/scraping#rtimes); however, the rtimes package has been removed from CRAN.

This is a classic problem with blogging - you can make new content easily but sustaining old content is harder to do!

**Comment by engineerchange** [comment]
I do see it was [abandoned](https://github.com/rOpenGov/rtimes). What a bummer.

Old blog posts... definitely a healthy mix of peril and fortune. Thanks for taking a look!
